import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';

import {
  generateInterviewQuestion,
  evaluateInterviewAnswer,
  generateFinalInterviewFeedback,
  saveInterview,
} from '../services/interviewService';

const FALLBACK_CONFIG = {
  role: 'Frontend Developer',
  experienceLevel: 'Entry Level',
  interviewType: 'Technical',
  questionCount: 10,
};

export default function InterviewSession() {
  const location = useLocation();
  const navigate = useNavigate();

  const config = location.state?.config || FALLBACK_CONFIG;
  const totalQuestions = config.questionCount || 10;

  // Questions are generated by the AI one at a time. The first one was
  // already generated on the setup page so the session can open instantly.
  const [sessionQuestions, setSessionQuestions] = useState(() => [
    location.state?.firstQuestion || '',
  ]);

  const [currentIndex, setCurrentIndex] = useState(0);
  const [userAnswers, setUserAnswers] = useState(
    Array(totalQuestions).fill('')
  );

  // One evaluation per answered question, collected as we move forward.
  const [evaluations, setEvaluations] = useState([]);

  const [sessionTimer, setSessionTimer] = useState(120);
  const [isRecording, setIsRecording] = useState(false);
  const [recordingSeconds, setRecordingSeconds] = useState(0);
  const [showFinishModal, setShowFinishModal] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isAdvancing, setIsAdvancing] = useState(false);
  const [error, setError] = useState('');

  // Redirect back to setup if the session config/first question is missing
  // (e.g. the page was opened directly instead of via the setup flow).
  useEffect(() => {
    if (!location.state?.config || !location.state?.firstQuestion) {
      navigate('/interview', { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const progressPercent = Math.round(
    ((currentIndex + 1) / totalQuestions) * 100
  );

  const answeredCount = userAnswers.filter(
    (ans) => ans && ans.trim()
  ).length;

  useEffect(() => {
    setSessionTimer(120);
  }, [currentIndex]);

  useEffect(() => {
    if (sessionTimer <= 0) return;

    const timer = setInterval(() => {
      setSessionTimer((prev) => prev - 1);
    }, 1000);

    return () => clearInterval(timer);
  }, [sessionTimer]);

  useEffect(() => {
    let timer;

    if (isRecording) {
      timer = setInterval(() => {
        setRecordingSeconds((prev) => prev + 1);
      }, 1000);
    } else {
      setRecordingSeconds(0);
    }

    return () => clearInterval(timer);
  }, [isRecording]);

  const formatTimer = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;

    return `${String(mins).padStart(2, '0')}:${String(secs).padStart(
      2,
      '0'
    )}`;
  };

  const handleTextChange = (value) => {
    const updated = [...userAnswers];
    updated[currentIndex] = value;
    setUserAnswers(updated);
  };

  const toggleRecording = () => {
    setIsRecording((prev) => !prev);
  };

  // Evaluates the answer for `index` (if not already evaluated) and
  // returns the updated evaluations array.
  const ensureEvaluated = async (index) => {
    if (evaluations[index]) {
      return evaluations;
    }

    const data = await evaluateInterviewAnswer({
      role: config.role,
      experienceLevel: config.experienceLevel,
      interviewType: config.interviewType,
      question: sessionQuestions[index],
      answer: userAnswers[index] || '',
    });

    const updated = [...evaluations];
    updated[index] = data.evaluation;
    setEvaluations(updated);

    return updated;
  };

  const handleNext = async () => {
    setIsRecording(false);
    setError('');

    if (currentIndex >= totalQuestions - 1) return;

    setIsAdvancing(true);

    try {
      // Evaluate the current answer in the background so the final
      // report has feedback for every question.
      await ensureEvaluated(currentIndex);

      // Generate the next question only if we haven't fetched it yet
      // (keeps Previous/Next free of re-generating questions).
      if (!sessionQuestions[currentIndex + 1]) {
        const data = await generateInterviewQuestion({
          role: config.role,
          experienceLevel: config.experienceLevel,
          interviewType: config.interviewType,
        });

        setSessionQuestions((prev) => {
          const updated = [...prev];
          updated[currentIndex + 1] = data.question;
          return updated;
        });
      }

      setCurrentIndex((prev) => prev + 1);
    } catch (err) {
      console.error(err);
      setError(
        err.response?.data?.detail ||
          err.message ||
          'Unable to reach the AI interviewer. Please try again.'
      );
    } finally {
      setIsAdvancing(false);
    }
  };

  const handlePrevious = () => {
    setIsRecording(false);

    if (currentIndex > 0) {
      setCurrentIndex((prev) => prev - 1);
    }
  };

  const handleOpenFinishModal = () => {
    setIsRecording(false);
    setShowFinishModal(true);
  };

  // ==============================
  // EVALUATE, GENERATE FEEDBACK & SAVE
  // ==============================

  const handleConfirmFinish = async () => {
    setShowFinishModal(false);
    setIsSubmitting(true);
    setError('');

    try {
      // Make sure the final question's answer is evaluated too.
      const finalEvaluations = await ensureEvaluated(currentIndex);

      const evaluationPayload = finalEvaluations.map((evaluation, index) => ({
        question: sessionQuestions[index],
        answer: userAnswers[index] || '',
        evaluation,
      }));

      const { feedback } = await generateFinalInterviewFeedback({
        role: config.role,
        experienceLevel: config.experienceLevel,
        interviewType: config.interviewType,
        evaluations: evaluationPayload,
      });

      const saved = await saveInterview({
        role: config.role,
        experience_level: config.experienceLevel,
        interview_type: config.interviewType,

        overall_score: feedback.overall_score,
        technical_accuracy: feedback.technical_accuracy,
        communication: feedback.communication,
        relevance: feedback.relevance,
        problem_solving: feedback.problem_solving,

        strengths: feedback.strengths,
        improvements: feedback.improvements,

        recommendation: feedback.recommendation,
        final_summary: feedback.final_summary,
      });

      navigate('/feedback', {
        state: {
          interview: saved,
          config,
          answers: userAnswers,
        },
      });
    } catch (err) {
      console.error(err);

      setError(
        err.response?.data?.detail ||
          err.message ||
          'Interview submission failed. Please try again.'
      );

      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-80px)] py-8 px-4 max-w-4xl mx-auto space-y-6">

      <div className="glass-card p-5 space-y-4 bg-white">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-sm font-black uppercase">
              {config.role} Interview
            </h2>

            <p className="text-xs text-slate-500">
              Question {currentIndex + 1} of {totalQuestions}
            </p>
          </div>

          <div className="bg-slate-900 text-white px-4 py-2 rounded-xl font-mono">
            ⏱ {formatTimer(sessionTimer)}
          </div>
        </div>

        <div>
          <div className="flex justify-between text-xs font-bold">
            <span>SESSION PROGRESS</span>
            <span>{progressPercent}%</span>
          </div>

          <div className="w-full bg-slate-100 h-2 rounded-full mt-2">
            <motion.div
              className="bg-blue-600 h-full rounded-full"
              animate={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>
      </div>

      <div className="p-4 rounded-2xl bg-slate-900 text-white">
        <h3 className="text-sm font-bold">
          AI Senior Evaluator
        </h3>

        <p className="text-xs text-slate-400">
          {isRecording
            ? 'Listening to voice response...'
            : 'Speech recognition active & monitoring'}
        </p>
      </div>

      {error && (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
          {error}
        </div>
      )}

      <AnimatePresence mode="wait">
        <motion.div
          key={currentIndex}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-card p-6 sm:p-8 space-y-6 bg-white"
        >
          <div>
            <span className="text-xs font-bold text-blue-600">
              QUESTION #{currentIndex + 1}
            </span>

            <h1 className="text-xl sm:text-2xl font-extrabold mt-2">
              {sessionQuestions[currentIndex] || 'Loading question…'}
            </h1>
          </div>

          {isRecording && (
            <div className="p-4 rounded-xl bg-red-50 border border-red-200">
              🔴 Recording... {formatTimer(recordingSeconds)}
            </div>
          )}

          <textarea
            rows={7}
            value={userAnswers[currentIndex]}
            onChange={(e) => handleTextChange(e.target.value)}
            placeholder="Type your answer here..."
            className="w-full p-4 rounded-2xl bg-slate-50 border border-slate-200 outline-none focus:border-blue-500 resize-none"
          />

          <div className="flex flex-col sm:flex-row gap-3 justify-between">

            <button
              onClick={handlePrevious}
              disabled={currentIndex === 0 || isAdvancing}
              className="btn-secondary px-5 py-2 disabled:opacity-40"
            >
              ← Previous
            </button>

            <button
              onClick={toggleRecording}
              disabled={isAdvancing || isSubmitting}
              className="bg-slate-100 px-5 py-2 rounded-xl font-bold disabled:opacity-40"
            >
              🎙 {isRecording ? 'Stop Recording' : 'Record Voice Answer'}
            </button>

            {currentIndex < totalQuestions - 1 ? (
              <button
                onClick={handleNext}
                disabled={isAdvancing || !userAnswers[currentIndex]?.trim()}
                className="btn-primary px-6 py-2 disabled:opacity-40"
              >
                {isAdvancing ? 'AI is thinking…' : 'Next Question →'}
              </button>
            ) : (
              <button
                onClick={handleOpenFinishModal}
                disabled={
                  isSubmitting || !userAnswers[currentIndex]?.trim()
                }
                className="btn-primary px-6 py-2 bg-emerald-600 disabled:opacity-40"
              >
                {isSubmitting
                  ? 'Generating your report…'
                  : 'Finish Interview →'}
              </button>
            )}
          </div>
        </motion.div>
      </AnimatePresence>

      {showFinishModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="bg-white rounded-2xl p-8 max-w-md w-full text-center space-y-5">

            <h3 className="text-xl font-bold">
              Finish Interview?
            </h3>

            <p className="text-sm text-slate-600">
              You answered {answeredCount} of {totalQuestions} questions.
              The AI will now evaluate your answers and generate a full
              report — this can take a few seconds.
            </p>

            <div className="flex gap-3">
              <button
                onClick={() => setShowFinishModal(false)}
                disabled={isSubmitting}
                className="btn-secondary flex-1 disabled:opacity-40"
              >
                Continue
              </button>

              <button
                onClick={handleConfirmFinish}
                disabled={isSubmitting}
                className="btn-primary flex-1 bg-emerald-600 disabled:opacity-60"
              >
                {isSubmitting ? 'Evaluating…' : 'Finish'}
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}